/**:
  ros__parameters:
    camera_names: [ "camera_1" ]
    camera_1:
      frame_id: "camera_top/camera_link"
      pixel_format: bgr8
      serial_no: 220300079
      fps: 15
      width: 1440
      height: 930
      flip_enable: false
      camera_info_url: "file:///home/zeys/projects/main_autoware/autoware/src/sensor_component/external/arena_camera/config/camera0_info.yaml"
